# This file was generated by the {rix} R package v0.18.2 on 2026-06-26
# with following call:
# >rix(date = "2026-03-11",
#  > r_pkgs = c("rvest",
#  > "devtools",
#  > "targets",
#  > "languageserver",
#  > "diffviewer"),
#  > system_pkgs = c("html-tidy",
#  > "gnumake",
#  > "pandoc"),
#  > tex_pkgs = c("collection-fontsextra"),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > r_ver = "4.5.3")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-03-11.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      devtools
      diffviewer
      languageserver
      rvest
      targets;
  };
  
  tex = (pkgs.texlive.combine {
    inherit (pkgs.texlive) 
      scheme-small
      collection-fontsextra;
  });
    
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      gnumake
      html-tidy
      nix
      pandoc
      R;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs tex system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
