---
title: "analyse"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{analyse}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE
)
```

```{r setup}
library(dtlscores)
library(dplyr, warn.conflicts = FALSE)
library(ggplot2)
```

Für uns sind die Teams der zweiten Bundesliga Süd in 2026 von Interesse:

```{r team_overview}
teams <- c("Exquisa Oberbayern", "TSV Monheim", "TT Buttenwiesen-Inningen", "VfL Kirchheim unter Teck", "TSV Unterföhring", "TSV Pfuhl", "TG Hanauerland", "KTV Ries") # nolint

routines |>
  filter(team %in% teams, end_value > 0) |>
  group_by(competition_url) |>
  filter(n() == 24) |>
  ungroup() |>
  select(team, competition_url, end_value) |>
  unique() |>
  left_join(competitions, by = join_by(competition_url)) |>
  filter(season == "2025") |>
  group_by(team) |>
  summarize(
    league = unique(league),
    total = mean(end_value) * 24
  ) |>
  arrange(desc(total)) |>
  rename(
    Team = "team",
    `Liga 2025` = "league",
    `Durschn. Endwert` = "total"
  ) |>
  gt::gt()
```

Stellt sich jetzt halt die Frage, wie ist das Ergebnis pro Gerät:


<!-- # ```{r} -->
<!-- # routines |> -->
<!-- #   filter(team %in% teams) |> -->
<!-- #   left_join(competitions, by = join_by(competition_url)) |> -->
<!-- #   filter(season == "2025") |> -->
<!-- #   summarize( -->
<!-- #     total = mean(end_value) * 4, -->
<!-- #     .by = c(team, event) -->
<!-- #   ) |> -->
<!-- #   tidyr::pivot_wider(names_from = event, values_from = total) |> -->
<!-- #   mutate(total = rowSums(across(-1), na.rm = TRUE)) |> -->
<!-- #   arrange(desc(total)) |> -->
<!-- #   gt::gt() -->
<!-- # ``` -->


```{r, fig.width = 12, fig.height = 8, out.width = "100%"}

min_value <- 7.5
max_value <- 15
value_range <- max_value - min_value

filtered_routines <- routines |>
  filter(team %in% teams) |>
  filter(end_value > min_value) |>
  left_join(competitions, by = join_by(competition_url)) |>
  filter(season == "2025") |>
  mutate(scaled_end_value = (end_value - min_value) / value_range) |>
  summarize(
            .by = c(team, gymnast_url, event),
            fit = list(fitdistrplus::fitdist(scaled_end_value, "beta", method = "mle"))) |>
  mutate(alpha = sapply(fit, \(x) x$estimate[["shape1"]]),
         beta = sapply(fit, \(x) x$estimate[["shape2"]])) |>
  select(-c(fit))

matchups <- beta_params |>
  filter(team == "TSV Monheim") |>
  dplyr::inner_join(beta_params, by = "event", suffix = c("_1", "_2")) |>
  filter(!team_2 == "TSV Monheim")

set.seed(123)
n_sims <- 100000

win_probs <- matchups |>
  rowwise() |>
  mutate(
    # Draw 100,000 samples for Team 1 and Team 2
    sim_1 = list(rbeta(n_sims, alpha_1, beta_1)),
    sim_2 = list(rbeta(n_sims, alpha_2, beta_2)),
    # Calculate the probability that Team 1 scores higher than Team 2
    prob_team_1_wins = mean(sim_1 > sim_2)
  ) |>
  # Clean up the raw simulation vectors from the final output
  select(-sim_1, -sim_2) |>
  ungroup()

ggplot(win_probs, aes(x = team_2, y = event, fill = prob_team_1_wins)) +
  geom_tile()
```

